name: Run tests and build the container images

on:
  release:
    types:
      - "published"
  push: 
    branches: 
      - "main"

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: ${{ github.repository_owner }}
  ALPHA_IMAGE_NAME: alpha
  BETA_IMAGE_NAME: beta

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - env:
          DEBUG_INFO1: ${{toJson(github)}}
        run: echo "$DEBUG_INFO1"
      - run: env | sort
      - name: Docker meta alpha
        id: meta-alpha
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.ALPHA_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}}
            type=sha
      - name: Docker meta beta
        id: meta-beta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.BETA_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}}
            type=sha
      - env:
          DEBUG_META_ALPHA: ${{toJson(steps.meta-alpha)}}
        run: echo "$DEBUG_META_ALPHA"
      - env:
          DEBUG_META_BETA: ${{toJson(steps.meta-alpha)}}
        run: echo "$DEBUG_META_BETA"
      - name: "Build and push alpha"
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta-alpha.outputs.tags }}
          annotations: ${{ steps.meta-alpha.outputs.annotations }}          
          context: './alpha'
      - name: "Build and push beta"
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta-beta.outputs.tags }}
          annotations: ${{ steps.meta-beta.outputs.annotations }}
          context: './beta'
