name: Run tests and build the container images

on:
  release:
    types:
      - "published"
  push: 
    branches: 
      - "main"

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: ${{ github.repository_owner }}
  ALPHA_IMAGE_NAME: alpha
  BETA_IMAGE_NAME: beta

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - env:
          DEBUG_INFO1: ${{toJson(github)}}
        run: echo "$DEBUG_INFO1"
      - run: env | sort
      - name: Docker meta
        id: meta-alpha
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.ALPHA_IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha         
      - env:
          DEBUG_INFO1: ${{toJson(steps.meta-alpha)}}
        run: echo "$DEBUG_INFO1"
      - name: "Build and push normal build - alpha"
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.ALPHA_IMAGE_NAME }}:${{ github.sha }}
          context: './alpha'
      - name: "Build and push normal build - beta"
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.ALPHA_IMAGE_NAME }}:${{ github.sha }}
          context: './beta'
      - name: "Build and push tagged/released build - alpha"
        uses: docker/build-push-action@v5
        if: github.event_name == 'release'
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.ALPHA_IMAGE_NAME }}:${{ github.sha }}
          context: './alpha'
      - name: "Build and push tagged/released build - beta"
        uses: docker/build-push-action@v5
        if: github.event_name == 'release'
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.ALPHA_IMAGE_NAME }}:${{ github.sha }}
          context: './alpha'
