name: Run tests and build the container images

on:
  release:
    types:
      - "published"
  push: 
    branches: 
      - "main"

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: ${{ github.repository_owner }}
  ALPHA_IMAGE_NAME: alpha
  BETA_IMAGE_NAME: beta

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up improved Docker Buildx support
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests for alpha
        run: npm run alpha-test
      - name: Run tests for beta
        run: npm run beta-test
      - name: Obtain tag information for alpha
        id: meta-alpha
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.ALPHA_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}}
            type=sha
      - name: Obtain tag information for beta
        id: meta-beta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.BETA_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}}
            type=sha
      - name: "Build and push alpha"
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta-alpha.outputs.tags }}
          annotations: ${{ steps.meta-alpha.outputs.annotations }}          
          context: './alpha'
          target: 'production-stage'
      - name: "Build and push beta"
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta-beta.outputs.tags }}
          annotations: ${{ steps.meta-beta.outputs.annotations }}
          context: './beta'
          target: 'production-stage'
